// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCXIP-KUxLE-luZSPkbQRAsnO-Y5zUhTU',
    appId: '1:150520404956:web:50878ec98bd31f86afcd19',
    messagingSenderId: '150520404956',
    projectId: 'filmload-c1064',
    authDomain: 'filmload-c1064.firebaseapp.com',
    databaseURL: 'https://filmload-c1064.firebaseio.com',
    storageBucket: 'filmload-c1064.appspot.com',
    measurementId: 'G-67WZQRR93M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaTpMiok_0eTJNL4Jid0IpmhEtxCy0wYk',
    appId: '1:150520404956:android:c0b21f112ba43378afcd19',
    messagingSenderId: '150520404956',
    projectId: 'filmload-c1064',
    databaseURL: 'https://filmload-c1064.firebaseio.com',
    storageBucket: 'filmload-c1064.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhNps9ScyZGlG3m5XZkFWu7VRpttKBgdk',
    appId: '1:150520404956:ios:72e985eab8f2a0beafcd19',
    messagingSenderId: '150520404956',
    projectId: 'filmload-c1064',
    databaseURL: 'https://filmload-c1064.firebaseio.com',
    storageBucket: 'filmload-c1064.appspot.com',
    androidClientId: '150520404956-ae81i5nnnv6aoqobrur68557jgrni2ei.apps.googleusercontent.com',
    iosClientId: '150520404956-juuecthqng145jltupb422tsk97q29ta.apps.googleusercontent.com',
    iosBundleId: 'com.example.reelClone',
  );
}
